if (NOT ${target} MATCHES Editor)
    if (${use_editor})
        target_link_libraries(${target} Editor)
    elseif(CMAKE_CONFIGURATION_TYPES)
        target_link_libraries(${target} $<$<CONFIG:DebugEditor>:Editor>)
        target_link_libraries(${target} $<$<CONFIG:ReleaseEditor>:Editor>)
        target_link_libraries(${target} $<$<CONFIG:DistributionEditor>:Editor>)
    endif()
endif()