SSL_VERTEX

port(VertexPos) in vec3 inPos;
port(VertexUV) in vec2 inUV;

port(FinalVertPos) out vec4 outPos;
port(FragUV) out vec2 outUV;

void main()
{
    vec2 posScreenSpace = vec2(inPos.x, inPos.y);
    vec2 vertexPosition_homoneneousspace = posScreenSpace - vec2(640,360);
    vertexPosition_homoneneousspace = vertexPosition_homoneneousspace / vec2(640,360);
    outPos = vec4(vertexPosition_homoneneousspace, 0.0, 1.0);

    outUV = inUV;
}