SSL_FRAGMENT

port(FragmentUV) in vec2 inUV;
port(FragColor) out vec4 color;

uniform sampler2D Texture;
uniform float smoothing;

void main()
{
    float cutoff = 0.5f;
    float dist = cutoff - texture(Texture, inUV).r;
    vec2 ddist = vec2(dfdx(dist), dfdy(dist));
    float pixelDist = dist / length(ddist);
    float opacity = clamp(0.5 - pixelDist, 0.0, 1.0);
    color = vec4(1, 1, 1, opacity);
}