function(setup_compile_options target)
    if (MSVC)
        target_compile_options(${target} PRIVATE /W4)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()

    if (WIN32)
        target_compile_options(${target} PRIVATE /wd4100)
    endif()
endfunction()