include_directories(${ENGINE_DIR}/src)
include_directories(${ENGINE_DIR}/sht_generated)
include_directories(${ENGINE_DIR}/third_party/bc7enc_rdo)
include_directories(${ENGINE_DIR}/third_party/stb-ae721c5)
include_directories(${ENGINE_DIR}/third_party/nlohmann_json-3.13.3)
include_directories(${ENGINE_DIR}/third_party/OpenFBX-365f52c)

if (${PLATFORM} MATCHES Windows)
    include(${ROOT_DIR}/CMake/windows/WindowsIncludeDirs.cmake)
elseif (${PLATFORM} MATCHES Linux)
    include(${ROOT_DIR}/CMake/linux/LinuxIncludeDirs.cmake)
elseif (${PLATFORM} MATCHES Mac)
    include(${ROOT_DIR}/CMake/mac/MacIncludeDirs.cmake)
endif ()