include_directories(${ENGINE_DIR}/src)
include_directories(${ENGINE_DIR}/third_party/Crunch2/inc)
include_directories(${ENGINE_DIR}/third_party/glew-2.1.0/include)
include_directories(${ENGINE_DIR}/third_party/stb-ae721c5)
include_directories(${ENGINE_DIR}/third_party/nlohmann_json-3.13.3)
include_directories(${ENGINE_DIR}/third_party/OpenFBX-365f52c)

if (${PLATFORM} MATCHES Windows)
    include(${ROOT_DIR}/CMake/WindowsIncludeDirs.cmake)
elseif (${PLATFORM} MATCHES Linux)
    include(${ROOT_DIR}/CMake/LinuxIncludeDirs.cmake)
elseif (${PLATFORM} MATCHES Mac)
    include(${ROOT_DIR}/CMake/MacIncludeDirs.cmake)
endif ()