if (${PLATFORM} MATCHES Windows)
    include(windows/WindowsLinkDirs)
elseif (${PLATFORM} MATCHES Linux)
    include(linux/LinuxLinkDirs)
elseif (${PLATFORM} MATCHES Mac)
    include(mac/MacLinkDirs)
endif()