#add_subdirectory(third_party/Crunch2)
add_subdirectory(third_party/bc7enc_rdo)
add_subdirectory(third_party/OpenFBX-365f52c)
if (${PLATFORM} MATCHES Windows)
    include(${ROOT_DIR}/CMake/WindowsThirdParty.cmake)
elseif (${PLATFORM} MATCHES Linux)
    include(${ROOT_DIR}/CMake/LinuxThirdParty.cmake)
elseif (${PLATFORM} MATCHES Mac)
    include(${ROOT_DIR}/CMake/MacThirdParty.cmake)
endif ()

#make third party libraries shut up
if (MSVC)
    target_compile_options(bc7enc PRIVATE /W0)
else()
    target_compile_options(bc7enc PRIVATE -w)
endif()